[tool.black]
target-version = ['py38']


[tool.towncrier]
package = "aioguest"
filename = "docs/source/history.rst"
directory = "newsfragments"
underlines = ["-", "~", "^"]
issue_format = "`#{issue} <https://github.com/oremanj/aioguest/issues/{issue}>`__"


[tool.pytest.ini_options]
xfail_strict = true
faulthandler_timeout = 60
filterwarnings = [
    "error",
]
